{
  AssertionError answer=null;
  try {
    block.invoke();
  }
 catch (  AssertionError e) {
    answer=e;
    System.out.println("Caught expected assertion failure: " + e);
  }
catch (  Exception e) {
    throw e;
  }
  if (answer == null) {
    throw new AssertionError("Expected an assertion error from block: " + block);
  }
  Asserts.LOG.info("Caught expected assertion failure: " + answer);
  return answer;
}
